#!/usr/bin/env expect

set cpus 1
set kernel [lindex $argv 0]
set kernel $::env(kernelFile)
set initrd $::env(initrd)
set cmdline $::env(linuxCmd)
set timeoutSeconds $::env(timeoutSeconds)

set qemuArgs "-machine q35,accel=kvm -m 4096 -nographic -net none -no-reboot -cpu host,+vmx -kernel \"$kernel\" -initrd \"$initrd\""

if {$cmdline != ""} {
    append qemuArgs " -append \"$cmdline\""
}

eval spawn qemu-system-x86_64 $qemuArgs

# Consider timeouts and early EOFs as failure.
expect_before {
    timeout { puts "Failed: Timeout";   exit 1 }
    eof     { puts "Failed: Early EOF"; exit 2 }
}

# Qemu might take some time to come up.
set timeout 60
expect "Linux version"

set timeout $timeoutSeconds

expect "SOTEST END"

close
